START:
  x: 0.04563
  y: 0.03022
  yaw_deg: -5.99

RACK_A:
  x: 0.013286
  y: 3.980360
  yaw_deg: 89.92 

RACK_B:
  x: 2.814964
  y: 4.082903
  yaw_deg: 95.52

WAIT:
  x: 2.61792
  y: 0.92301
  yaw_deg: -0.83