START:
  x: 0.04563
  y: 0.03022
  yaw_deg: -5.99

RACK_A:
  x: -0.28336
  y: 3.66136
  yaw_deg: 87.79 

RACK_B:
  x: 2.7840
  y: 3.9015
  yaw_deg: 1.4705

WAIT:
  x: 2.61792
  y: 0.92301
  yaw_deg: -0.83