START:
  x: 0.04563
  y: 0.03022
  yaw_deg: -5.99

RACK_A:
  x: -0.004017
  y: 3.953716
  yaw_deg: -95.4

RACK_B:
  x: 2.78324
  y: 4.07872
  yaw_deg: -105.21

WAIT:
  x: 2.72313
  y: 1.00833
  yaw_deg: 160.57