START:
  x: 0.04563
  y: 0.03022
  yaw_deg: -5.99

RACK_A:
  x: -0.12488
  y: 1.62557
  yaw_deg: -13.14

RACK_B:
  x: 2.78324
  y: 4.07872
  yaw_deg: -108.21

MID_A:
  x: 2.47639
  y: 0.75845
  yaw_deg: 100.00